title: React fetch
description: >- # this means to ignore newlines until "baseurl:"
  Write a short description of your project here.
remote_theme: pmarsceill/just-the-docs
# Optional settings
search_enabled: true
